namespace ExtendedTooltip.src.Settings
{
    public enum SettingKey
    {
        Citizen = 0,
        CitizenState = 1,
        CitizenHappiness = 2,
        CitizenEducation = 3,
        Company = 4,
        CompanyOutput = 5,
        Efficiency = 6,
        Employee = 7,
        ParkingFacility = 8,
        ParkingFees = 9,
        ParkingCapacity = 10,
        Park = 11,
        ParkMaintenance = 12,
        PublicTransport = 13,
        PublicTransportWaitingPassengers = 14,
        PublicTransportWaitingTime = 15,
        Road = 16,
        RoadLength = 17,
        RoadUpkeep = 18,
        RoadCondition = 19,
        School = 20,
        SchoolStudentCapacity = 21,
        Spawnable = 23,
        SpawnableLevel = 24,
        SpawnableLevelDetails = 25,
        SpawnableHousehold = 26,
        SpawnableHouseholdDetails = 27,
        SpawnableRent = 28,
        SpawnableZoneInfo = 35,
        Vehicle = 29,
        VehiclePassengerDetails = 30,
        VehicleDriver = 31,
        VehicleState = 32,
        VehiclePostvan = 33,
        VehicleGarbageTruck = 34,
        UseOnPressOnly = 91,
        DisableMod = 90
    }
}
